/* Auto-generated file. Do not edit manually. */

#ifndef EMBEDDED_PP_STM32U031_VREFBUF_HPP
#define EMBEDDED_PP_STM32U031_VREFBUF_HPP

#include <cstdint>
#include "Core/Common.hpp"
#include "Core/BitField.hpp"
#include "Core/Register.hpp"

/** @brief VREFBUF address block description */
namespace STM32U031::VREFBUF {

    /** @brief VREFBUF control and status register */
    using VREFBUF_CSR = ::EmbeddedPP::LowLevel::Register<std::uint32_t, 0x0, ::EmbeddedPP::LowLevel::Accessibility::ReadWrite>;
    /** @brief Voltage reference buffer mode enable This bit is used to enable the voltage reference buffer mode. */
    using VREFBUF_CSR_ENVR = ::EmbeddedPP::LowLevel::BitField<std::uint32_t, 0, 1, ::EmbeddedPP::LowLevel::Accessibility::ReadWrite>;
    /** @details Possible values:
     *          - B_0x0: Internal voltage reference mode disable (external voltage reference mode). (value: 0)
     *          - B_0x1: Internal voltage reference mode (reference buffer enable or hold mode) enable. (value: 1)
     */
        /** @brief Internal voltage reference mode disable (external voltage reference mode). */
    constexpr std::uint32_t VREFBUF_CSR_ENVR_B_0x0 = 0;
        /** @brief Internal voltage reference mode (reference buffer enable or hold mode) enable. */
    constexpr std::uint32_t VREFBUF_CSR_ENVR_B_0x1 = 1;

    /** @brief High impedance mode This bit controls the analog switch to connect or not the V<sub>REF+</sub> pin. Refer to Table172: VREF buffer modes for the mode descriptions depending on ENVR bit configuration. */
    using VREFBUF_CSR_HIZ = ::EmbeddedPP::LowLevel::BitField<std::uint32_t, 1, 1, ::EmbeddedPP::LowLevel::Accessibility::ReadWrite>;
    /** @details Possible values:
     *          - B_0x0: V<sub>REF+</sub> pin is internally connected to the voltage reference buffer output. (value: 0)
     *          - B_0x1: V<sub>REF+</sub> pin is high impedance. (value: 1)
     */
        /** @brief V<sub>REF+</sub> pin is internally connected to the voltage reference buffer output. */
    constexpr std::uint32_t VREFBUF_CSR_HIZ_B_0x0 = 0;
        /** @brief V<sub>REF+</sub> pin is high impedance. */
    constexpr std::uint32_t VREFBUF_CSR_HIZ_B_0x1 = 1;

    /** @brief Voltage reference scale This bit selects the value generated by the voltage reference buffer. */
    using VREFBUF_CSR_VRS = ::EmbeddedPP::LowLevel::BitField<std::uint32_t, 2, 1, ::EmbeddedPP::LowLevel::Accessibility::ReadWrite>;
    /** @details Possible values:
     *          - B_0x0: Voltage reference set to V<sub>REF_OUT1</sub> (around 2.0481V). (value: 0)
     *          - B_0x1: Voltage reference set to V<sub>REF_OUT2</sub> (around 2.51V). (value: 1)
     */
        /** @brief Voltage reference set to V<sub>REF_OUT1</sub> (around 2.0481V). */
    constexpr std::uint32_t VREFBUF_CSR_VRS_B_0x0 = 0;
        /** @brief Voltage reference set to V<sub>REF_OUT2</sub> (around 2.51V). */
    constexpr std::uint32_t VREFBUF_CSR_VRS_B_0x1 = 1;

    /** @brief Voltage reference buffer ready */
    using VREFBUF_CSR_VRR = ::EmbeddedPP::LowLevel::BitField<std::uint32_t, 3, 1, ::EmbeddedPP::LowLevel::Accessibility::ReadWrite>;
    /** @details Possible values:
     *          - B_0x0: the voltage reference buffer output is not ready. (value: 0)
     *          - B_0x1: the voltage reference buffer output reached the requested level. (value: 1)
     */
        /** @brief the voltage reference buffer output is not ready. */
    constexpr std::uint32_t VREFBUF_CSR_VRR_B_0x0 = 0;
        /** @brief the voltage reference buffer output reached the requested level. */
    constexpr std::uint32_t VREFBUF_CSR_VRR_B_0x1 = 1;

    /** @brief VREFBUF calibration control register */
    using VREFBUF_CCR = ::EmbeddedPP::LowLevel::Register<std::uint32_t, 0x4, ::EmbeddedPP::LowLevel::Accessibility::ReadWrite>;
    /** @brief None */
    using VREFBUF_CCR_TRIM = ::EmbeddedPP::LowLevel::BitField<std::uint32_t, 0, 6, ::EmbeddedPP::LowLevel::Accessibility::ReadWrite>;
}

#endif
